left_eye/pan_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: left_eye/pan_joint
  joint_speed: 0.8
  motor:
    id: 3 
    init: 512
    min: 0
    max: 1023

left_eye/tilt_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: left_eye/tilt_joint
  joint_speed: 0.8
  motor:
      id: 4
      init: 512
      min: 0
      max: 1023
